# Generated by Django 5.2.10 on 2026-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_labreport_soapnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
