# Generated by Django 5.2.10 on 2026-02-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='embedding_json',
            field=models.TextField(blank=True, help_text='Stores the JSON representation of the patient vector embedding', null=True),
        ),
    ]
