# Generated by Django 5.2.10 on 2026-04-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_embedding_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Auto-extracted text for AI search', null=True),
        ),
    ]
