# Generated by Django 5.2.10 on 2026-05-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_labreport_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='breakfast_time',
            field=models.CharField(default='08:30 AM', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='dinner_time',
            field=models.CharField(default='08:30 PM', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='lunch_time',
            field=models.CharField(default='01:30 PM', max_length=20),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions/')),
                ('extracted_text', models.TextField(blank=True, help_text='Raw OCR text representation', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('timing', models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('night', 'night'), ('any', 'any')], default='any', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='patients.prescription')),
            ],
        ),
    ]
