# Generated by Django 5.2.10 on 2026-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='List of patient food/drug allergies', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active')], default='new', max_length=10),
        ),
    ]
