# Generated by Django 5.2.10 on 2026-05-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patient_allergies_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='ocr_error',
            field=models.TextField(blank=True, help_text='Error message if OCR failed', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
