# Generated by Django 5.2.10 on 2026-05-23 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_city'),
        ('patients', '0006_labreport_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('General Ward', 'General Ward'), ('Semi-Private', 'Semi-Private'), ('Private', 'Private'), ('ICU', 'ICU')], default='General Ward', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_room', to='patients.patient')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hospitals.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'room_number')},
            },
        ),
    ]
